[package]
name = "stratus"
version = "0.1.0"
authors = ["alexa <alexa.griffin42@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"

[dependencies]
stratus-macros = { version = "0.1.0", path = "./stratus-macros" }
once_cell = "1.2.0"